passoffice = git
createimagemap = yes
compare = none
createhistory = no
createskos = yes
usefirstmap = yes
#gitpath = /Geonovum/iso-19107-datatypen
sfconformance = 2
#mapping = MIM-NEN3610-ONTDUBBELD
assocbyreference        = yes
createmimformat = yes
mimformattype = xml
nativescalars = no
